export type INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const INCREMENT_COUNTER: INCREMENT_COUNTER = "INCREMENT_COUNTER";
export type RESET_COUNTER = "RESET_COUNTER";
export const RESET_COUNTER: RESET_COUNTER = "RESET_COUNTER";


// NEW
export type CHANGE_FILTER = "CHANGE_FILTER";
export const CHANGE_FILTER: CHANGE_FILTER = "CHANGE_FILTER";
export type CHANGE_DATA_CELL = "CHANGE_DATA_CELL";
export const CHANGE_DATA_CELL: CHANGE_DATA_CELL = "CHANGE_DATA_CELL";
