export type INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const INCREMENT_COUNTER: INCREMENT_COUNTER = "INCREMENT_COUNTER";
export type RESET_COUNTER = "RESET_COUNTER";
export const RESET_COUNTER: RESET_COUNTER = "RESET_COUNTER";
